export const CRIAR_TAREFA = "CRIAR_TAREFA";
export const EDITAR_TAREFA = "EDITAR_TAREFA";
export const DELETAR_TAREFA = "DELETAR_TAREFA";
export const LISTAR_TAREFAS = "LISTAR_TAREFAS";
export const SELECIONAR_TAREFA = "SELECIONAR_TAREFA";
export const SETAR_ERRO = "SETAR_ERRO";
